openapi: 3.0.0
info:
  title: Knnect Home REST API
  description: 'REST API to interact with SMART HOME services '
  contact:
    name: Kasun Thennakoon
    email: tmkasun@gmail.com
  license:
    name: MIT
  version: "1.0"
servers:
- url: http://localhost:5000/apis
  description: Dev
- url: https://home.knnect.com/apis
  description: Prod
paths:
  /switches/{switchID}:
    get:
      tags:
      - Switchers
      summary: Get Sonoff switch Info by Switch ID
      description: Retrieve the information of the Sonoff switch with the matching
        switch ID.
      operationId: get_switches_switch_id
      parameters:
      - name: switchID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Device information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
              examples:
                Device info:
                  value:
                    seq: 2
                    error: 0
                    data:
                      switch: "off"
                      startup: "off"
                      pulse: "off"
                      pulseWidth: 500
                      ssid: eWeLink
                      otaUnlock: false
                      fwVersion: 3.5.0
                      deviceid: 100000140e
                      bssid: ec:17:2f:3d:15:e
                      signalStrength: -25
      x-openapi-router-controller: swagger_server.controllers.switchers_controller
    post:
      tags:
      - Switchers
      description: Add new sOnOff switch
      operationId: post_switches_switch_id
      parameters:
      - name: switchID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
      deprecated: true
      x-openapi-router-controller: swagger_server.controllers.switchers_controller
  /switches/{switchID}/state:
    get:
      tags:
      - Switchers
      summary: Get Sonoff switch state by Switch ID
      description: "[Not mapped to sonoff API] Retrieve the information of the Sonoff\
        \ switch On/Off state with the matching switch ID."
      operationId: get_switches_state
      parameters:
      - name: switchID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Device information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
              examples:
                Device info:
                  value:
                    seq: 2
                    error: 0
                    data:
                      switch: "off"
                      startup: "off"
                      pulse: "off"
                      pulseWidth: 500
                      ssid: eWeLink
                      otaUnlock: false
                      fwVersion: 3.5.0
                      deviceid: 100000140e
                      bssid: ec:17:2f:3d:15:e
                      signalStrength: -25
        "404":
          description: Switch ID Not Found
      x-openapi-router-controller: swagger_server.controllers.switchers_controller
    post:
      tags:
      - Switchers
      description: Control the switch
      operationId: post_switches_state
      parameters:
      - name: switchID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Control switch on/off state
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwitchStateRequest'
            examples:
              Turn on switch:
                value:
                  isOn: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwitchStateResponse'
      x-openapi-router-controller: swagger_server.controllers.switchers_controller
  /switches:
    get:
      tags:
      - Switchers
      summary: Get Sonoff switch Info by Switch ID
      description: "[Not mapped to sonoff API] Retrieve the information of the Sonoff\
        \ switch with the matching switch ID."
      operationId: get_switches
      responses:
        "200":
          description: Device information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DevicesList'
              examples:
                Device info list:
                  value:
                  - seq: 2
                    error: 0
                    data:
                      switch: "off"
                      startup: "off"
                      pulse: "off"
                      pulseWidth: 500
                      ssid: eWeLink
                      otaUnlock: false
                      fwVersion: 3.5.0
                      deviceid: 100000140e
                      bssid: ec:17:2f:3d:15:e
                      signalStrength: -25
        "404":
          description: User Not Found
      x-openapi-router-controller: swagger_server.controllers.switchers_controller
  /banks/{bankName}:
    get:
      tags:
      - Banking
      summary: Get Bank Details
      description: Get bank details
      operationId: get_details_by_bank_name
      parameters:
      - name: bankName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInfo'
              examples: {}
      x-openapi-router-controller: swagger_server.controllers.banking_controller
  /banks:
    get:
      tags:
      - Banking
      summary: Get all available Banks
      description: Get bank details
      operationId: get_all_details
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BanksList'
              examples: {}
      x-openapi-router-controller: swagger_server.controllers.banking_controller
  /banks/{bankName}/{accountID}:
    get:
      tags:
      - Banking
      summary: Get specific bank account details
      description: Get bank account details
      operationId: get_one_account_details
      parameters:
      - name: bankName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: accountID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInfo'
              examples: {}
      x-openapi-router-controller: swagger_server.controllers.banking_controller
  /banks/{bankName}/{accountID}/trasfer:
    post:
      tags:
      - Banking
      description: Transfer money to know account
      operationId: post_bank_transfers
      parameters:
      - name: bankName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: accountID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountID_trasfer_body'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-openapi-router-controller: swagger_server.controllers.banking_controller
components:
  schemas:
    SwitchStateResponse:
      title: SwitchStateResponse
      required:
      - data
      - deviceid
      type: object
      properties:
        deviceid:
          type: string
        data:
          $ref: '#/components/schemas/SwitchStateResponse_data'
      description: Payload schema for toggling switch state On or Off
      example:
        data:
          switch: "on"
        deviceid: deviceid
      x-examples:
        Switch On:
          deviceid: ""
          data:
            switch: "on"
          value:
            deviceid: ""
            data:
              switch: "on"
    PowerOn:
      required:
      - data
      - deviceid
      type: object
      properties:
        deviceid:
          type: string
        data:
          $ref: '#/components/schemas/PowerOn_data'
      x-examples:
        Power-on State:
          value:
            deviceid: ""
            data:
              startup: stay
    WiFiSignalStrength:
      required:
      - data
      - error
      - seq
      type: object
      properties:
        seq:
          type: number
        error:
          type: number
        data:
          $ref: '#/components/schemas/WiFiSignalStrength_data'
      x-examples:
        WiFi Signal Strength:
          seq: 2
          error: 0
          data:
            signalStrength: -67
          value:
            seq: 2
            error: 0
            data:
              signalStrength: -67
    Inching:
      required:
      - data
      - deviceid
      type: object
      properties:
        deviceid:
          type: string
        data:
          $ref: '#/components/schemas/Inching_data'
      x-examples:
        Inching Pulse On:
          deviceid: ""
          data:
            pulse: "on"
            pulseWidth: 2000
          value:
            deviceid: ""
            data:
              pulse: "on"
              pulseWidth: 2000
    DeviceInfo:
      required:
      - data
      - error
      - seq
      type: object
      properties:
        seq:
          type: number
        error:
          type: number
        data:
          $ref: '#/components/schemas/DeviceInfo_data'
      description: Get Device Info
      example:
        data:
          pulseWidth: 1.46581298050294517310021547018550336360931396484375
          startup: startup
          bssid: bssid
          signalStrength: 5.962133916683182377482808078639209270477294921875
          pulse: pulse
          fwVersion: fwVersion
          ssid: ssid
          otaUnlock: true
          deviceid: deviceid
          switch: switch
        error: 6.02745618307040320615897144307382404804229736328125
        seq: 0.80082819046101150206595775671303272247314453125
      x-examples:
        Get Device Info:
          seq: 2
          error: 0
          data:
            switch: "off"
            startup: "off"
            pulse: "off"
            pulseWidth: 500
            ssid: eWeLink
            otaUnlock: false
            fwVersion: 3.5.0
            deviceid: 100000140e
            bssid: ec:17:2f:3d:15:e
            signalStrength: -25
          value:
            seq: 2
            error: 0
            data:
              switch: "off"
              startup: "off"
              pulse: "off"
              pulseWidth: 500
              ssid: eWeLink
              otaUnlock: false
              fwVersion: 3.5.0
              deviceid: 100000140e
              bssid: ec:17:2f:3d:15:e
              signalStrength: -25
    EmptyRequest:
      required:
      - deviceid
      type: object
      properties:
        deviceid:
          type: string
        data:
          type: object
      x-examples:
        empty post request for GET:
          deviceid: ""
          data: {}
          value:
            deviceid: ""
            data: {}
    DevicesList:
      minItems: 1
      uniqueItems: true
      type: array
      description: Get list of all sOnOff devices
      items:
        $ref: '#/components/schemas/DevicesList_inner'
      x-examples:
        one device sample:
        - seq: 2
          error: 0
          data:
            switch: "off"
            startup: "off"
            pulse: "off"
            pulseWidth: 500
            ssid: eWeLink
            otaUnlock: false
            fwVersion: 3.5.0
            deviceid: 100000140e
            bssid: ec:17:2f:3d:15:e
            signalStrength: -25
    SwitchStateRequest:
      title: SwitchStateRequest
      required:
      - isOn
      type: object
      properties:
        isOn:
          type: boolean
      description: Request payload of switching off/on
      x-examples:
        Switch on request:
          value:
            isOn: true
    AccountInfo:
      title: AccountInfo
      required:
      - account
      - amount
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        account:
          minLength: 1
          type: string
        amount:
          type: number
      description: Account details
      example:
        amount: 0.80082819046101150206595775671303272247314453125
        name: name
        account: account
      x-examples:
        seylan:
          name: Seylan
          account: "0654788946"
          amount: 245123.23000000001047737896442413330078125
    BanksList:
      minItems: 1
      uniqueItems: true
      type: array
      description: List of available bank configs
      items:
        $ref: '#/components/schemas/BanksList_inner'
      x-examples:
        seylan:
        - name: Seylan
          accountNumber: "231232143214"
          user: knnect
    accountID_trasfer_body:
      required:
      - amount
      - to
      type: object
      properties:
        to:
          minLength: 1
          type: string
        amount:
          type: number
      x-examples:
        example-1:
          to: account
          amount: 1231.23000000000001818989403545856475830078125
    inline_response_200:
      required:
      - reference
      - trasnfered
      type: object
      properties:
        trasnfered:
          type: boolean
        reference:
          type: string
      example:
        reference: reference
        trasnfered: true
      x-examples:
        example-1:
          trasnfered: true
    SwitchStateResponse_data:
      required:
      - switch
      type: object
      properties:
        switch:
          minLength: 1
          type: string
          enum:
          - "on"
          - "off"
      example:
        switch: "on"
    PowerOn_data:
      required:
      - startup
      type: object
      properties:
        startup:
          minLength: 1
          type: string
          description: "on: the device is on when power supply is recovered.\noff:\
            \ the device is off when power supply is recovered.\nstay: the device\
            \ status keeps as the same as the state before power supply is gone"
          example: "on"
          enum:
          - "on"
          - "off"
          - stay
    WiFiSignalStrength_data:
      required:
      - signalStrength
      type: object
      properties:
        signalStrength:
          type: number
          description: "The WiFi signal strength currently received by the device,\
            \ negative integer, dBm"
    Inching_data:
      required:
      - pulse
      type: object
      properties:
        pulse:
          minLength: 1
          type: string
          description: "on: activate the inching function;\noff: disable the inching\
            \ function"
          enum:
          - "on"
          - "off"
        pulseWidth:
          type: number
          description: "Required when “pulse” is on, pulse time length, positive integer,\
            \ ms, only supports multiples of 500 in range of 500~3600000\n"
    DeviceInfo_data:
      required:
      - bssid
      - deviceid
      - fwVersion
      - otaUnlock
      - pulse
      - pulseWidth
      - signalStrength
      - ssid
      - startup
      - switch
      type: object
      properties:
        switch:
          minLength: 1
          type: string
        startup:
          minLength: 1
          type: string
        pulse:
          minLength: 1
          type: string
        pulseWidth:
          type: number
        ssid:
          minLength: 1
          type: string
        otaUnlock:
          type: boolean
        fwVersion:
          minLength: 1
          type: string
        deviceid:
          minLength: 1
          type: string
        bssid:
          minLength: 1
          type: string
        signalStrength:
          type: number
      example:
        pulseWidth: 1.46581298050294517310021547018550336360931396484375
        startup: startup
        bssid: bssid
        signalStrength: 5.962133916683182377482808078639209270477294921875
        pulse: pulse
        fwVersion: fwVersion
        ssid: ssid
        otaUnlock: true
        deviceid: deviceid
        switch: switch
    DevicesList_inner:
      required:
      - data
      - error
      - seq
      type: object
      properties:
        seq:
          type: number
        error:
          type: number
        data:
          required:
          - bssid
          - deviceid
          - fwVersion
          - otaUnlock
          - pulse
          - pulseWidth
          - signalStrength
          - ssid
          - startup
          - switch
          type: object
          properties:
            switch:
              minLength: 1
              type: string
            startup:
              minLength: 1
              type: string
            pulse:
              minLength: 1
              type: string
            pulseWidth:
              type: number
            ssid:
              minLength: 1
              type: string
            otaUnlock:
              type: boolean
            fwVersion:
              minLength: 1
              type: string
            deviceid:
              minLength: 1
              type: string
            bssid:
              minLength: 1
              type: string
            signalStrength:
              type: number
          example:
            pulseWidth: 1.46581298050294517310021547018550336360931396484375
            startup: startup
            bssid: bssid
            signalStrength: 5.962133916683182377482808078639209270477294921875
            pulse: pulse
            fwVersion: fwVersion
            ssid: ssid
            otaUnlock: true
            deviceid: deviceid
            switch: switch
      example:
        data:
          pulseWidth: 1.46581298050294517310021547018550336360931396484375
          startup: startup
          bssid: bssid
          signalStrength: 5.962133916683182377482808078639209270477294921875
          pulse: pulse
          fwVersion: fwVersion
          ssid: ssid
          otaUnlock: true
          deviceid: deviceid
          switch: switch
        error: 6.02745618307040320615897144307382404804229736328125
        seq: 0.80082819046101150206595775671303272247314453125
    BanksList_inner:
      required:
      - accountNumber
      - name
      - user
      type: object
      properties:
        name:
          minLength: 1
          type: string
        accountNumber:
          minLength: 1
          type: string
        user:
          minLength: 1
          type: string
      example:
        name: name
        accountNumber: accountNumber
        user: user

